# Generated by Django 4.2.5 on 2023-09-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_name_case_ignore',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
