# Generated by Django 4.2.5 on 2023-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_manager_app', '0002_remove_tag_unique_tag_name_case_ignore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
